language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.4
  - 1.5
  - nightly

branches:
  only:
    - master

notifications:
  email: false

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())';

jobs:
  allow_failures:
  - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.5
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
